services:
  database:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "database_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"


volumes:
  rabbitmq_data:
  database_data:
